apiVersion: v1
kind: ReplicationController
metadata:
 name: mynginx-rc
spec:
 replicas: 3
 selector:
   app: myngix
 template:
   metadata:
     labels:
       app: myngix
   spec:
      containers:
      - name: mynginxcontainer
        image: nginx
        ports:
        - containerPort: 80